server:
  port: 8081
spring:
  application:
    name: accounts
  profiles:
    active: dev
  cloud:
    bootstrap:
      enabled: true
    vault:
      uri: http://localhost:8500
      authentication: token
      token: AccountsService
      kv:
        enabled: true
        backend: secret
        profile-separator: "-"
        application-name: accounts
  config:
    import:
    - "vault://"
    - "optional:configserver:http://localhost:8080"


management:
  endpoints:
    web:
      exposure:
        include: refresh,env,health,info

logging:
  level:
    org.springframework.vault: DEBUG
    org.springframework.cloud.vault: DEBUG
